Daniil klmuk config
3mdeb/workstation-config pull request #5
Opened 2023-06-13 16:29 UTC by DaniilKl

2023-06-13 16:40 UTC, macpijan requested changes

2023-06-13 17:03 UTC, macpijan commented on extra_vars/dklimuk.yml
> +zshrc_template: "zshrc.j2"
@DaniilKl The same comment as here: https://github.com/3mdeb/workstation-config/pull/2#discussion_r1228403621

2023-06-21 14:31 UTC, DaniilKl commented
In [commit](https://github.com/3mdeb/workstation-config/pull/5/commits/79e9bc71aa85899ed1e809b28867d99c46983f8c) file `extra_vars/dklimuk.yml` has been added. In [commit](https://github.com/3mdeb/workstation-config/pull/5/commits/79e9bc71aa85899ed1e809b28867d99c46983f8c)  file `extra_vars/user-template.yml` has been edited to math the same file from `main` branch.

2023-06-21 14:50 UTC, DaniilKl commented
@macpijan everything is done and ready for review. Changes are explained in [this thread](https://github.com/3mdeb/workstation-config/pull/5#issuecomment-1600951189).

2023-06-21 15:59 UTC, merged